language: objective-c
matrix:
  include:
    - osx_image: xcode7.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8

git:
  submodules: false
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"

script:
  - set -o pipefail
  - carthage bootstrap
  - xcodebuild test -scheme Rex-Mac | xcpretty -c
  - xcodebuild test -scheme Rex-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme Rex-tvOS -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme Rex-watchOS -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty -c

notifications:
  email: false
